steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cloudside-academy/wordpress-saai-demo/custom-wordpress:v1', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cloudside-academy/wordpress-saai-demo/custom-wordpress:v1']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials saai-charan-cluster \
          --region us-central1 \
          --project cloudside-academy

  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=saai-charan-cluster'
    args: ['apply', '-f', 'wordpress-deployment.yaml']

  - name: 'gcr.io/cloud-builders/curl'
    secretEnv: ['SLACK_WEBHOOK']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ WordPress deployed successfully to GKE!"}' \
          "$$SLACK_WEBHOOK"

availableSecrets:
  secretManager:
    - versionName: projects/769170094354/secrets/saai-build-test/versions/latest
      env: 'SLACK_WEBHOOK'
