apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: default
  labels:
    app: scg-wordpress
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: scg-wordpress
  template:
    metadata:
      labels:
        app: scg-wordpress
    spec:
      containers:
      - name: scg-wordpress
        image: us-central1-docker.pkg.dev/cloudside-academy/wordpress-sai-demo/my-wordpress:v1
        ports:
        - containerPort: 80
          name: http
        env:
        - name: WORDPRESS_DB_HOST
          value: "10.103.0.5:3306"
        - name: WORDPRESS_DB_NAME
          value: "psc-instance"
        - name: WORDPRESS_DB_USER
          value: "admin"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: db_password
        - name: WORDPRESS_DEBUG
          value: "true"
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define('WP_HOME', 'https://scg.cloudside.dev');
            define('WP_SITEURL', 'https://scg.cloudside.dev');
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
      volumes:
      - name: wordpress-data
        emptyDir: {}

