apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scg-wordpress
  template:
    metadata:
      labels:
        app: scg-wordpress
    spec:
      containers:
      - name: scg-wordpress
        image: us-central1-docker.pkg.dev/cloudside-academy/wordpress-sai-demo/my-wordpress:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: scg-wordpress
spec:
  type: ClusterIP
  selector:
    app: scg-wordpress
  ports:
    - port: 80
      targetPort: 80

